### ISSUE TITLE
Dell products possibly affected too

### ISSUE THREAD

**Issue by Firminator** [YfryTchsGD/Log4jAttackSurface#10]
https://www.dell.com/support/search/en-us#q=log4j&sort=date%20descending

Wyse
SupportAssist Enterprise
EMC Data Protection Manager

**Comment by blighter** [comment]
https://www.dell.com/support/kbdoc/en-uk/000194414/dell-response-to-apache-log4j-remote-code-execution-vulnerability

Dell confirmed the below products are impacted with a TBD for fix

Data Domain OS
Dell EMC Cloud Disaster Recovery
Dell EMC ECS
Dell EMC Enterprise Storage Analytics for vRealize Operations
Dell EMC ObjectScale
Dell EMC PowerFlex Appliance
Dell EMC PowerFlex Rack
Dell EMC PowerProtect DP Series Appliance (iDPA)
Dell EMC PowerStore
Dell EMC RecoverPoint
Dell EMC Streaming Data Platform
Dell EMC Unity
Dell EMC VxRail
Dell Open Management Enterprise - Modular
OpenManage Enterprise
SupportAssist Enterprise
Unisphere Central
Wyse Management Suite
Wyse Windows Embedded

**Comment by Firminator** [comment]
Yup Dell being the only vendor who puts this advisory behind a login wall.
